app_name: '420swagmoney'
reddit_boot: 'swagmoneyfordays by 420blazeitswagmoney'

reddit_id: 'u5sanUaINhJ2KQ'
reddit_secret: '2ufw5fy7lJoAIjH5s4RI3z3JBOU'

username: '420blazeitswagmoney'
password: 'defexe96'
